<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<?php
// print_r(json_encode($products));
echo $this->tag->linkTo(
    '/product',
    'Go Back!'
);   
if ($products->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Product ID</th>
            <th>Product Name</th>
            <th>Product Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="5">Total Number of Products: <?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $k) { ?>
            <tr>
                <td><?php echo $k->product_id; ?></td>
                <td><?php echo $k->product_name; ?></td>
                <td><?php echo $k->product_description; ?></td>
                <td><?php echo $k->tags; ?></td>
                <td><?php echo $k->price; ?></td>
                <td><?php echo $k->stock; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
        }
        ?>
